const D={
living:[
['QUESTION','How can we relate to an emotion before we know what to call it?','Not every emotion arrives with a clear name or cause. Some feelings first appear as tension, heaviness, restlessness, or an indistinct bodily atmosphere. Living Object explores how a physical interface might create a space for encountering these pre-verbal emotional states without demanding immediate explanation.'],
['AMBIGUOUS STATE + CONTEXT','Some emotions are present before they are understandable.','Emotional experience does not always begin with conscious interpretation. A feeling may be too subtle, mixed, or disconnected from an obvious cause to be easily verbalized. In these moments, the difficulty is not necessarily the absence of emotion, but the gap between feeling something and being able to understand what that feeling is.<br><br>SEQUENCE<br>FELT → UNNAMED → VERBALIZED'],
['BARRIER + INSIGHT','Emotional sensemaking does not always need to begin with naming.','Many interfaces for emotional reflection begin by asking users to identify, label, or record what they feel. Living Object begins from a different possibility: before an emotion can be interpreted, could it first be held in a physical relationship? Instead of forcing an ambiguous feeling into an immediate category, the project explores whether touch, proximity, waiting, and repeated encounters can give the feeling a temporary form.'],
['INTERFACE STRATEGY','From emotional identification to emotional encounter.','Living Object translates an internal and ambiguous emotional state into a physical relationship. The object does not tell the user what they feel. Instead, its presence, material behavior, and responsiveness provide something that can be approached, touched, observed, and revisited.'],
['EXPERIENCE + RESPONSE','A slow cycle of encounter.','The interaction is intentionally slow. Rather than producing a single correct response, the object creates a repeated cycle of approaching, touching, observing, waiting, and returning.<br><br>EXPERIENCE<br>NOTICE → APPROACH → TOUCH → OBSERVE → STAY → RETURN'],
['EVIDENCE + DEVELOPMENT','What should be documented as the work develops.','The project should be evidenced through emotional framing, interaction studies, material studies, and object-behavior experiments. Each test should be edited as Question → Test → Observation → Design Decision, rather than as an archive of sketches.<br><br>EVIDENCE<br>• Concept sketches<br>• Material tests<br>• Interaction diagrams<br>• Object behavior videos<br>• Use scenarios<br>• Exhibition documentation<br>• Reflection notes'],
['REFLECTION','Holding ambiguity before interpretation.','Living Object reframes emotional ambiguity as something that does not always need to be immediately resolved. It explores how an interface might first create a relationship with what is still difficult to name, allowing touch and physical presence to precede interpretation.']],
pms:[
['QUESTION','How can bodily patterns provide context when emotional changes feel unexplained?','Emotional changes associated with the menstrual cycle can be difficult to interpret in the moment. When a shift in mood feels disconnected from an obvious cause, uncertainty can turn into confusion, anxiety, or self-blame. This project explores how a product–service system can make relationships between bodily rhythm, timing, and emotional changes easier to recognize.'],
['AMBIGUOUS STATE + CONTEXT','The feeling is perceptible. Its context is not.','The project focuses on the interpretive gap between experiencing an emotional change and understanding the context in which it occurs. The goal is not to determine a single biological cause for emotion, but to help users notice possible patterns across timing, bodily rhythm, and mood.'],
['BARRIER + INSIGHT','Patterns become useful only when they can be connected to lived experience.','Cycle information, bodily signals, and mood records often exist as separate pieces of data. Yet a user’s question is rarely simply “What is my cycle phase?” It is closer to “Could what I am feeling now be related to what is happening in my body?” The design opportunity is therefore not only sensing or tracking, but translating separate signals into a careful, non-deterministic interpretation.'],
['INTERFACE STRATEGY','Recognize → Interpret → Respond.','Recognize: make cyclical changes and emotional records visible. Interpret: connect information across timing, body rhythm, and mood instead of presenting isolated numbers. Respond: offer supportive options without treating the pattern as a diagnosis or warning.<br><br>CORE SYSTEM<br>RECOGNIZE → INTERPRET → RESPOND'],
['EXPERIENCE + RESPONSE','Possibility, not certainty.','The user notices that something feels different, checks the system, sees relevant patterns and timing, interprets the change as a possible recurring relationship, chooses a supportive action, and gradually builds a longer-term picture of their own patterns.<br><br>USER JOURNEY<br>FEEL → NOTICE → CONNECT → INTERPRET → RESPOND → REFLECT'],
['EVIDENCE + DEVELOPMENT','Evidence for a product–service system.','The portfolio should show an information architecture, product touchpoint, clear sensing status, core UI screens, user journey, and testing of comprehension, tone, trust, and usefulness. Any estradiol or sweat-sensing mechanism must be explicitly labeled as tested, proposed, or speculative.<br><br>POSSIBLE RESPONSES<br>• Rest<br>• Warmth<br>• Light movement<br>• Journaling<br>• Conversation<br>• Breathing<br>• Sleep<br>• Tactile calming<br>• Environment adjustment'],
['REFLECTION','Information as emotional mediation.','This project explores information as a form of emotional mediation. Rather than reducing emotional change to biological data, the system uses bodily patterns as contextual information that can help users interpret their experience with less uncertainty and more room for self-directed response.']],
child:[
['QUESTION','How might narrative help children engage with difficult emotional questions?','Emotional screening often relies on direct verbal questions. For children, however, abstract questions about mood and psychological experience can be difficult to understand or answer comfortably. This research investigates how the same emotional questions can be reframed through storytelling and narrative interaction.'],
['AMBIGUOUS STATE + CONTEXT','The difficulty may lie not only in the emotion, but also in the way the question is asked.','Children may experience an emotion without having the language, context, or distance needed to explain it directly. A questionnaire asks them to move immediately from internal experience to an explicit verbal answer.'],
['BARRIER + INSIGHT','Narrative creates distance without removing the emotional question.','Instead of removing sensitive content, the project embeds screening questions into situations, characters, and story events. This creates a layer of narrative mediation between the child and the emotional question.'],
['INTERFACE STRATEGY','Translate direct questions into narrative contexts.','Screening questions were translated into three narrative contexts—Reality World, Transition World, and Dream World. Instead of encountering each item as an isolated statement, children engage with emotional situations within an unfolding story.<br><br>NARRATIVE WORLDS<br>REALITY WORLD → TRANSITION WORLD → DREAM WORLD<br><br>TRANSLATION<br>DIRECT QUESTION → CHARACTER / SITUATION / STORY → REFLECTION / RESPONSE'],
['EXPERIENCE + RESPONSE','Story → interpretation → self-reference → response.','The game does not change the emotional topic being asked about. It changes the interaction through which the question becomes understandable and approachable.'],
['EVIDENCE + DEVELOPMENT','Qualitative research, not diagnostic validation.','Children aged 11–13 experienced both game-based and text-based formats and participated in qualitative interviews. The study should be presented around comprehension, comfort, and emotional articulation, not diagnostic accuracy. The study received Seoul National University IRB approval, with parental consent and child assent.<br><br>MY ROLE<br>Qualitative interview guide → Result framing → Discussion points → Insight synthesis → Game-content refinement'],
['REFLECTION','Narrative as mediation.','This research showed me that emotional interfaces are not only about what information is presented, but also about the distance, context, and medium through which a person encounters it. Narrative became my first way of exploring how design can mediate an emotion before asking for direct articulation.']],
lockin:[
['QUESTION','When does stimulation begin to feel like rest?','Short-form media fits easily into small gaps in everyday life. It is quick, low-effort, and immediately rewarding, which makes scrolling feel like a convenient form of rest. LOCKIN began by questioning whether this sense of rest actually corresponds to cognitive recovery.'],
['AMBIGUOUS STATE + CONTEXT','A break can feel complete without being restorative.','Because each piece of short-form content is brief and complete, users can enter and leave the experience with almost no preparation. Yet the stream continues to provide rapid information and stimulation, allowing passive scrolling to become embedded across many everyday contexts.<br><br>INSIGHT<br>SHORT → COMPLETE → LOW EFFORT → FEELS LIKE REST'],
['BARRIER + INSIGHT','Low effort is easily mistaken for recovery.','The research identified a pattern in which short, complete, low-effort content feels like rest, even when users later report wasted time, emptiness, sleep or focus disruption, and regret. The team interviewed eight university students; I debriefed the interviews and organized the findings into six initial insight directions.'],
['INTERFACE STRATEGY','Make the moment of choice visible.','LOCKIN does not simply block short-form media. It intervenes at the moment the user opens it and presents the viewing decision in relation to time, routine, and alternative recovery activities.<br><br>SERVICE FLOW<br>ONBOARDING → ACTIVITY SETUP → INTERVENTION → ALTERNATIVE ACTION → ROUTINE REPORT'],
['EXPERIENCE + RESPONSE','Context → intervention → choice → action → report.','The service uses onboarding, alternative-activity setup, a short-form intervention overlay, an alternative-action mode, and routine reports to help users reinterpret rest as an intentional routine rather than passive stimulation.'],
['EVIDENCE + DEVELOPMENT','Compress to the strongest research and UI evidence.','Show one key research insight, a small amount of interview synthesis, and 3–5 core UI screens: intervention overlay, alternative recommendation, action mode, and routine report. Prototype status: Figma screen design / prototype.'],
['REFLECTION','Information can reveal a cognitive pattern at the moment of choice.','LOCKIN shifted my attention from controlling behavior to making an invisible cognitive pattern perceptible. Information became a way of creating a moment in which users could reconsider what they understood as rest and choose how to respond.']],
squeeze:[
['QUESTION','Can emotion be responded to physically before it needs to be explained?','Stress often creates a desire for immediate physical release, yet many familiar coping activities require particular amounts of time, space, or preparation. SQUEEZE ME explores touch as a small and immediate form of affective response.'],
['AMBIGUOUS STATE + CONTEXT','Knowing that I am stressed does not always tell me what to do with it.','Stress and emotional overload can occur anywhere—during work, study, travel, or social situations. Although people develop personal coping methods such as music, exercise, meditation, food, or rest, these responses are not always available at the moment stress appears.'],
['BARRIER + INSIGHT','The gap can be between recognition and an available response.','The project focuses on moments when a person already knows they are stressed but has no small, immediate action available. Instead of asking the user to analyze the source of stress, the design provides a tactile outlet that can be used in place.'],
['INTERFACE STRATEGY','Translate emotional load into tactile action.','SQUEEZE ME is a soft tactile object that converts emotional pressure into repetitive hand actions. Rather than asking the user to identify or analyze the source of stress, the interface provides resistance, deformation, and recovery through material interaction.<br><br>INTERACTION VOCABULARY<br>SQUEEZE → PRESS → RUB → KNEAD'],
['EXPERIENCE + RESPONSE','Pressure becomes something physically graspable.','The user reaches for the object, repeats squeezing, pressing, rubbing, or kneading actions, experiences changing pressure and resistance, and then returns to the previous activity. The portfolio should avoid claiming clinically proven stress reduction.'],
['EVIDENCE + DEVELOPMENT','Material behavior is the evidence.','Material experiments included food-safe platinum silicone, three strengths of gel wax, coconut wax, varied wax mixtures, three surface patterns, and flatter versus dome-like forms. Early elasticity tests used flour, followed by in-class tests and later wax-based iterations.<br><br>MATERIAL EXPLORATION<br>Platinum silicone → Gel wax: three strengths → Coconut wax → Wax mixtures → Three surface patterns → Flat and dome forms'],
['REFLECTION','Touch as an affective interface.','SQUEEZE ME became an early seed for my interest in affective interfaces. It showed me that an emotional interface does not always need to interpret a feeling; sometimes the interface can first provide a physical way to respond to it.']],
balium:[
['QUESTION','Can furniture make an unconscious bodily habit perceptible without prescribing a single correct posture?','Balium explores bodily self-awareness through responsive furniture. It asks whether subtle physical feedback can draw attention to an unconscious sitting habit without forcing the body into a fixed “correct” position.'],
['AMBIGUOUS STATE + CONTEXT','Comfort can hide repetition.','While sitting, the body naturally moves toward positions that feel comfortable. As those positions become habitual, the user may stop consciously noticing how posture is repeatedly distributed or maintained.'],
['BARRIER + INSIGHT','The body can adapt before attention catches up.','The connection to the wider portfolio is not mental health directly, but self-awareness. The body may adapt toward comfort before the user consciously notices the pattern.'],
['INTERFACE STRATEGY','Feedback instead of correction.','Balium explores responsive furniture that makes sitting patterns physically noticeable through subtle feedback. Rather than forcing the user into a predetermined “correct” position, the chair is conceived as an interface for bodily awareness.<br><br>SYSTEM<br>BODY POSITION → SENSOR → PHYSICAL FEEDBACK → AWARENESS → SELF-ADJUSTMENT'],
['EXPERIENCE + RESPONSE','Posture → sensing → feedback → awareness.','The user sits naturally. As a posture pattern continues, the furniture provides physical feedback that draws attention back to the body. The user can then choose whether and how to reposition.'],
['EVIDENCE + DEVELOPMENT','Be explicit about prototype scope.','Physical chair form and sensors were developed. The final actuation / moving feedback mechanism was not fully completed and should be stated clearly in the portfolio.<br><br>PROTOTYPE STATUS<br>Completed: physical form → Completed: sensors integrated → Incomplete: final actuation / moving mechanism'],
['REFLECTION','From emotional awareness to bodily self-awareness.','Balium expanded my interest in perception from emotional awareness toward bodily self-awareness. It introduced physical feedback as another way an interface can make an otherwise unnoticed state perceptible.']]};
const k=new URLSearchParams(location.search).get('project')||'living',names=['01','02','03','04','05','06','07'];
document.querySelectorAll('.section').forEach(x=>x.remove());
document.querySelector('.footer').insertAdjacentHTML('beforebegin',`${k==='lockin'?'<section class="prototype-videos" aria-label="LOCKIN prototype videos"><span class="label">PROTOTYPE INTERACTIONS · USER FLOW</span><div class="video-grid"><article><b>01 / ONBOARDING</b><video controls playsinline preload="metadata"><source src="assets/projects/lockin-prototype-03.mp4" type="video/mp4"></video></article><article><b>02 / CHOICE</b><video controls playsinline preload="metadata"><source src="assets/projects/lockin-prototype-01.mp4" type="video/mp4"></video></article><article><b>03 / FEED</b><video controls playsinline preload="metadata"><source src="assets/projects/lockin-prototype-02.mp4" type="video/mp4"></video></article></div></section>':k==='child'?'<section class="child-video" aria-label="Child Depression Screening Game prototype"><span class="label">PROTOTYPE VIDEO</span><video controls playsinline preload="metadata"><source src="assets/projects/child-prototype.mp4" type="video/mp4"></video></section>':''}${D[k].map((s,i)=>`<section class="section"><span class="label">${names[i]} ${s[0]}</span><div><h2>${s[1]}</h2><p>${s[2]}</p></div><div class="mini">MEDIA</div></section>`).join('')}`);
