const data={
living:['01','LIVING OBJECT','THESIS · EMOTION · TOUCH / OBJECT','#7a4ab8',['Living Object','Pre-verbal / not-yet-named emotion','Emotion can be felt before its cause, meaning, or language becomes clear.','Touch / Physical Object','Embodied interaction','Touch / Observe / Stay / Care / Return'],['How can we relate to an emotion before we know what to call it?','Some emotions are present before they are understandable.','Interpretation can arrive too early.','A physical relationship can hold what is still unnamed.','Touch, observe, stay, care, return.','Physical presence can precede interpretation.']],
pms:['02','PMS PRODUCT–SERVICE','THESIS · EMOTION / BODY · INFORMATION / PRODUCT','#2b73c2',['PMS Product–Service','Unexplained cyclical emotional change','The relationship to bodily rhythm is not visible.','Information + Product','Sensing / Logging / Pattern interpretation','Recognize / Interpret / Respond'],['How can bodily patterns provide context when emotional changes feel unexplained?','The feeling is perceptible. Its context is not.','Patterns become useful once they are made visible.','Information becomes an interpretive companion.','Recognize, interpret, respond.','Context changes how emotional change is understood.']],
child:['03','CHILD DEPRESSION SCREENING GAME','RESEARCH FOUNDATION · EMOTION · NARRATIVE','#db3d40',['Child Depression Screening Game','Difficult-to-articulate emotional experience','Direct screening questions can be uncomfortable.','Narrative','Storytelling / Character mediation','Understand / Relate / Articulate'],['How might narrative help children engage with difficult emotional questions?','The difficulty may lie in the way the question is asked.','Narrative creates distance without removing relevance.','Screening becomes an encounter with a story.','Understand, relate, articulate.','The interface changes the conditions of the question.']],
lockin:['04','LOCKIN','EXPLORATION · COGNITION · INFORMATION','#2e6eba',['LOCKIN','Stimulation disguised as rest','Short-form media can feel like recovery.','Information','Contextual intervention / Routine feedback','Pause / Reinterpret / Choose'],['When does stimulation begin to feel like rest?','A break can feel complete without being restorative.','Low effort is not always recovery.','Intervene at the moment of opening.','Pause, reinterpret, choose.','Information can create a moment for reconsideration.']],
squeeze:['05','SQUEEZE ME','EXPLORATION · EMOTION · TOUCH','#7a4ab8',['SQUEEZE ME','Stress / Emotional overload','An immediate response may be unavailable.','Touch','Tactile material interaction','Squeeze / Press / Rub / Knead'],['Can emotion be responded to physically before it needs to be explained?','Recognition does not always tell us what to do next.','The gap is between recognition and response.','Material behavior turns pressure into action.','Squeeze, press, rub, knead.','An interface can first provide a way to respond.']],
balium:['06','BALIUM','EXPLORATION · BODY · PHYSICAL FEEDBACK','#407d47',['Balium','Unnoticed sitting pattern','Habitual posture can escape attention.','Physical feedback','Sensor / Responsive furniture','Notice / Self-adjust'],['How can subtle physical feedback draw attention to unconscious sitting habits?','The body can adapt before attention catches up.','The unnoticed pattern is difficult to change.','Responsive furniture becomes an interface for awareness.','Notice, then self-adjust.','Perception can extend to bodily self-awareness.']]};
const key=new URLSearchParams(location.search).get('project')||'living',p=data[key]||data.living,labels=['PROJECT NAME','AMBIGUOUS STATE','BARRIER','MEDIUM','INTERFACE MODE','RESPONSE'],copy=['This project examines an ambiguous everyday state and looks for a way to make it more perceptible, interpretable, and actionable without demanding an immediate explanation.','The interface focuses on the gap between what is experienced and what can be consciously understood in the moment.','The design frames this gap as a condition for reflection rather than a problem to be immediately resolved.','Its strategy uses material, information, or narrative interaction to create a meaningful relationship with the state.','The resulting experience supports a small, deliberate response in the moment.','The project expands the wider portfolio’s exploration of affective interfaces.'];
document.documentElement.style.setProperty('--accent',p[3]);document.title=`${p[1]} — Raina`;document.querySelector('#project').innerHTML=`<header class="head"><a class="all-projects" href="index.html?page=projects">← ALL PROJECTS</a><nav class="project-nav" aria-label="Portfolio navigation"><a href="index.html?page=intro">00 / INTRO</a><a href="index.html?page=position">01 / POSITION</a><a href="index.html?page=projects">02 / PROJECTS</a><a class="active" href="#top">03 / ${p[1]}</a></nav></header><div class="title"><span class="number">${p[0]}</span><h1>${p[1]}</h1><p>${p[2]}</p></div><div class="media">PROJECT MEDIA / HERO</div><p class="frame-label">PROJECT FRAME</p><div class="frame">${p[4].map((v,i)=>`<div><b>${labels[i]}</b><span>${v}</span></div>`).join('')}</div>${p[5].map((h,i)=>`<section class="section"><span class="label">${String(i+1).padStart(2,'0')} ${['QUESTION','AMBIGUOUS STATE + CONTEXT','BARRIER + INSIGHT','EXPERIENCE','EVIDENCE + DEVELOPMENT','REFLECTION'][i]}</span><div><h2>${h}</h2><p>${copy[i]}</p></div><div class="mini">MEDIA</div></section>`).join('')}<footer class="footer"><a href="#top">BACK TO TOP ↑</a></footer>`;
if (key === 'lockin') { document.querySelector('.media').classList.add('lockin-media'); document.querySelector('.media').innerHTML = '<img src="assets/projects/lockin-hero.jpg" alt="LOCKIN app screens" />'; }
if (key === 'living') { document.querySelector('.media').classList.add('living-media'); document.querySelector('.media').innerHTML = '<img src="assets/projects/living-hero.png" alt="Living Object tactile press and texture pieces" />'; }
if (key === 'squeeze') { document.querySelector('.media').classList.add('squeeze-media'); document.querySelector('.media').innerHTML = '<img src="assets/projects/squeeze-hero-cropped.png" alt="SQUEEZE ME tactile object studies" />'; }
if (key === 'balium') { document.querySelector('.media').classList.add('balium-media'); document.querySelector('.media').innerHTML = '<img src="assets/projects/balium-hero.jpg" alt="BALIUM responsive chair prototype" />'; }
